languageCode = "en"
languageName = "English"
weight = 1
title = "Piotr Olchawa"

[params]
displayName = "EN"
isoCode = "en"
rtl = false
dateFormat = "2 January 2006"

[author]
image = "IMG_0953.png"
name = "Piotr Olchawa"
headline = "Hello there!"
links = [ { github = "https://github.com/2easy" }, { linkedin = "https://www.linkedin.com/in/polchawa/" }, { x-twitter = "https://x.com/piotr_olchawa" } ]
