# Site settings
title: Piotr Olchawa
email: piotrekolchawa@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Software security, programming.
baseurl: "" # the subpath of your site, e.g. /blog
url: "0x41.xyz" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: 2easy_sec
github_username:  2easy

# Build settings
markdown: kramdown
theme: minima
gems:
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock
